"""Generated request builders package for generated_requests."""

from pfmsoft.eve_link.language import LangType

X_COMPATIBILITY_DATE: str = "2026-08-04"
ACCEPT_LANGUAGE: LangType = "en"
X_TENANT: str = "tranquility"

from . import (
    access_list,
    activities,
    alliance,
    assets,
    calendar,
    character,
    clones,
    contacts,
    contracts,
    corporation,
    corporation_projects,
    dogma,
    faction_warfare,
    fittings,
    fleets,
    freelance_jobs,
    incursions,
    industry,
    insurance,
    killmails,
    location,
    loyalty,
    mail,
    market,
    meta,
    military_campaigns,
    planetary_interaction,
    routes,
    search,
    skills,
    sovereignty,
    status,
    structures,
    universe,
    user_interface,
    wallet,
    wars,
)

__all__ = [
    "access_list",
    "activities",
    "alliance",
    "assets",
    "calendar",
    "character",
    "clones",
    "contacts",
    "contracts",
    "corporation",
    "corporation_projects",
    "dogma",
    "faction_warfare",
    "fittings",
    "fleets",
    "freelance_jobs",
    "incursions",
    "industry",
    "insurance",
    "killmails",
    "location",
    "loyalty",
    "mail",
    "market",
    "meta",
    "military_campaigns",
    "planetary_interaction",
    "routes",
    "search",
    "skills",
    "sovereignty",
    "status",
    "structures",
    "universe",
    "user_interface",
    "wallet",
    "wars",
]
